SRCS := $(wildcard src/*.cpp)
OBJS := $(SRCS:.cpp=.o)

CXXFLAGS := \
	-Iinclude \
	-I../include \
	-fPIC

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@

default: $(OBJS)
	$(CXX) $(OBJS) -o lib$(LOCAL_MODULE).so -shared

clean:
	@find \( \
		-type f \
		-executable -o \
		-name "*.so" -o \
		-name "*.o" -o \
		-name "core" \
		\) \
	   	-exec rm -v {} \;
