sources := $(wildcard src/*.cpp)
objects := $(sources:.cpp=.o)


CXXFLAGS = -Iinclude

.cpp.o:
	$(CXX) -c $< -o $@

.o.so:
	$(CXX) $< -o $@ -shared

clean:
	find \( \
		-type f \
		-executable -o \
		-name "*.so" -o \
		-name "*.o" -o \
		-name "core" \
		\) \
	   	-exec rm -v {} \;
